In [ ]:
import numpy as np
a= np.array([[1,2,3,4],[2,3,4,5]])
a.shape

(2, 4)

In [ ]:
a= np.zeros((2,3))
a






array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a=np.array([[1,6,7,8],[6,7,8,9]])
a

array([[1, 6, 7, 8],
       [6, 7, 8, 9]])

In [ ]:
b=np.array([[3,4,5,6],[5,6,7,8]])
b

array([[3, 4, 5, 6],
       [5, 6, 7, 8]])

In [ ]:
d=np.concatenate ((a,b),axis=1)
d


array([[1, 6, 7, 8, 3, 4, 5, 6],
       [6, 7, 8, 9, 5, 6, 7, 8]])

In [ ]:
d= np.stack((a,b),axis=1)
d

array([[[1, 6, 7, 8],
        [3, 4, 5, 6]],

       [[6, 7, 8, 9],
        [5, 6, 7, 8]]])

In [ ]:
d=np.hstack((a,b))
d

array([[1, 6, 7, 8, 3, 4, 5, 6],
       [6, 7, 8, 9, 5, 6, 7, 8]])

In [ ]:
d=np.vstack((a,b))
d

array([[1, 6, 7, 8],
       [6, 7, 8, 9],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

workshop1


question no 1
1. Initialize an empty array with size 2X2.

In [ ]:
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

2. Initialize an all one array with size 4X2.

In [ ]:
b=np.ones((4,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:

a= np.full((3,2),5)
a


array([[5, 5],
       [5, 5],
       [5, 5]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}


In [ ]:
a=np.zeros_like((4,5))
a

array([0, 0])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
a=np.ones_like((4,5))
a

array([1, 1])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [ ]:
new_list=np.array([1,2,3,4])
new_list


array([1, 2, 3, 4])

In [ ]:
#2


1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
a=np.arange(1,50)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
a=np.array([[0,1,2],[3,4,5],[6,7,8]])
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}


In [ ]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.


In [ ]:
a=np.random.random(30)
b=a.mean()
b

0.5355467756737766

5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
a=np.random.random((10,10))
b=a.min()
c=a.max()


print(b,c)

0.019735775019323665 0.9896663683971272


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
a=np.array([1,2,0,0,4,0])
b=a[::-1]
b


array([0, 4, 0, 0, 2, 1])

8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np
arr_border=np.ones((5,5))
arr_border[1:-1,1:-1]=0
arr_border



arr_checkerboard=np.zeros((8,8))
arr_checkerboard[1::2,::2]=1
arr_checkerboard[::2,1::2]=1
arr_checkerboard


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1.	Add the two array.


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
arr_add=x+y
print("X + Y = ",arr_add)
arr_add=v+w
print("V + W = ",arr_add)

X + Y =  [[ 6  8]
 [10 13]]
V + W =  [20 22]


2.	Subtract the two array.


In [ ]:
arr_sub=x-y
print("\nX - Y = ",arr_sub)
arr_sub=v-w
print("V - W = ",arr_sub)


X - Y =  [[-4 -4]
 [-4 -3]]
V - W =  [-2 -2]


3. Multiply the array with any integers of your choice.

In [ ]:
arr_mul=x*3
print("\nX * 3 = ",arr_mul)
arr_mul=y*3
print("Y * 3 = ",arr_mul)


X * 3 =  [[ 3  6]
 [ 9 15]]
Y * 3 =  [[15 18]
 [21 24]]


4.	Find the square of each element of the array.

In [ ]:
arr_square=x**2
print("\nSquare of X = ",arr_square)
arr_square=y**2
print("Square of Y = ",arr_square)
arr_square=v**2
print("Square of V = ",arr_square)
arr_square=w**2
print("Square of W = ",arr_square)


Square of X =  [[ 1  4]
 [ 9 25]]
Square of Y =  [[25 36]
 [49 64]]
Square of V =  [ 81 100]
Square of W =  [121 144]


5.	Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
arr_dot_pro=np.dot(v,w)
print("\nDot product of V and W = ",arr_dot_pro)
arr_dot_pro=np.dot(x,v)
print("Dot product of X and V = ",arr_dot_pro)
arr_dot_pro=np.dot(x,y)
print("Dot product of X and Y = ",arr_dot_pro)


Dot product of V and W =  219
Dot product of X and V =  [29 77]
Dot product of X and Y =  [[19 22]
 [50 58]]


6.	Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
arr_concat=np.concatenate((x,y),axis=0)
print("\nConcatenate X and Y along row = ",arr_concat)
arr_concat=np.concatenate((v,w))
print("Concatenate V and W along column = ",arr_concat)



Concatenate X and Y along row =  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate V and W along column =  [ 9 10 11 12]


7.	Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
arr_concat=np.concatenate((x,v))
print("\nConcatenate X and V along row = ",arr_concat)
# ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
# The error occurs because X is 2 dimensional array and array V has one dimension. SO in this case concatenation is not possible.


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations: • For the following arrays: A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]); Prove following with Numpy:

Prove A.(A)−1 = I.
Prove AB != BA.
Prove (AB)T = (B)T(A)T

In [ ]:
from abc import ABC
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#1 Prove A.(A)−1 != I.
A_inverse=np.linalg.inv(A)
prove_1=np.dot(A,A_inverse)
print("Prove 1.(A)−1 = I = \n",prove_1)

#2 Prove AB != BA.
AB=np.dot(A,B)
BA=np.dot(B,A)
print("\nProve 2\n",AB,"\n    != \n",BA)

#3 Prove (AB)T = (B)T(A)T
AB_transpose = np.transpose(AB)
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
BA_transpose = np.dot(B_transpose,A_transpose)
print("\nProve 3\n(AB)T = \n",AB_transpose)
print("\n(B)T(A)T = \n",BA_transpose)

Prove 1.(A)−1 = I = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Prove 2
 [[23 13]
 [51 29]] 
    != 
 [[36 44]
 [13 16]]

Prove 3
(AB)T = 
 [[23 51]
 [13 29]]

(B)T(A)T = 
 [[23 51]
 [13 29]]


• Solve the following system of Linear equation using Inverse Methods.

                2x − 3y + z = −1
                x − y + 2z = −3
                3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [ ]:
N=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
P=np.array([-1,-3,9])

N_inv=np.linalg.inv(N)
X=np.dot(N_inv,P)
print("\n[ x, y, z]= ",X)



[ x, y, z]=  [ 2.  1. -2.]


Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.



In [ ]:
import time
import numpy as np

# Create lists and arrays of size 1,000,000
size = 1000000
list1 = list(range(size))
list2 = list(range(size))
array1 = np.arange(size)
array2 = np.arange(size)

# Element-wise addition using Python lists
start_time = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
end_time = time.time()
print("Element-wise addition")
print("Time taken using Python lists:", end_time - start_time, "seconds")

# Element-wise addition using NumPy arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

# Element-wise multiplication using Python lists
start_time= time.time()
result_list= [x * y for x, y in zip(list1, list2)]
end_time= time.time()
print("\nElement-wise multiplication")
print("Time taken using Python lists:", end_time - start_time, "seconds")

# Element-wise multiplication using NumPy arrays
start_time= time.time()
result_array= array1 * array2
end_time= time.time()
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

# dot-product using Python lists
start_time= time.time()
result_list= [x * y for x, y in zip(list1, list2)]
end_time= time.time()
print("\nDot product")
print("Time taken using Python lists:", end_time - start_time, "seconds")

# dot-product using NumPy arrays
start_time= time.time()
result_array= np.dot(array1, array2)
end_time= time.time()
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")



Element-wise addition
Time taken using Python lists: 0.15005993843078613 seconds
Time taken using NumPy arrays: 0.0034096240997314453 seconds

Element-wise multiplication
Time taken using Python lists: 0.07944273948669434 seconds
Time taken using NumPy arrays: 0.0035529136657714844 seconds

Dot product
Time taken using Python lists: 0.1076970100402832 seconds
Time taken using NumPy arrays: 0.0018727779388427734 seconds


Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Create matrices of size 1000x1000
size = 1000
matrix1_list = [[1 for _ in range(size)] for _ in range(size)]
matrix2_list = [[2 for _ in range(size)] for _ in range(size)]
matrix1_array = np.ones((size, size))
matrix2_array = np.full((size, size), 2)

# Matrix multiplication using Python lists
start_time = time.time()
result_list = [[sum(a * b for a, b in zip(row_a, col_b))
                for col_b in zip(*matrix2_list)] for row_a in matrix1_list]
end_time = time.time()
print("Time taken using Python lists:", end_time - start_time, "seconds")

# Matrix multiplication using NumPy arrays
start_time = time.time()
result_array = np.dot(matrix1_array, matrix2_array)
end_time = time.time()
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

Time taken using Python lists: 112.4311740398407 seconds
Time taken using NumPy arrays: 0.05900740623474121 seconds
